# Form implementation generated from reading ui file 'Dondathang.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(622, 733)
        Dialog.setStyleSheet("background-color: #0F1E25;")
        self.lb_tddh = QtWidgets.QLabel(parent=Dialog)
        self.lb_tddh.setGeometry(QtCore.QRect(240, 20, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_tddh.setFont(font)
        self.lb_tddh.setStyleSheet("color: white;")
        self.lb_tddh.setObjectName("lb_tddh")
        self.de_ndh = QtWidgets.QDateEdit(parent=Dialog)
        self.de_ndh.setGeometry(QtCore.QRect(130, 120, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.de_ndh.setFont(font)
        self.de_ndh.setStyleSheet("QDateEdit{\n"
"    background-color: #A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;\n"
"}\n"
"\n"
"QDateEdit:hover{\n"
"    border: 1px solid #60a5fa;\n"
"}\n"
"\n"
"QDateEdit::drop-down{\n"
"    border: none;\n"
"}\n"
"\n"
"QDateEdit::down-arrow{\n"
"    image: none;\n"
"}")
        self.de_ndh.setObjectName("de_ndh")
        self.lb_ncc = QtWidgets.QLabel(parent=Dialog)
        self.lb_ncc.setGeometry(QtCore.QRect(20, 70, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_ncc.setFont(font)
        self.lb_ncc.setStyleSheet("color: white;")
        self.lb_ncc.setObjectName("lb_ncc")
        self.cb_ncc = QtWidgets.QComboBox(parent=Dialog)
        self.cb_ncc.setGeometry(QtCore.QRect(130, 70, 471, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.cb_ncc.setFont(font)
        self.cb_ncc.setStyleSheet("QComboBox {\n"
"    background-color:#A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid #60a5fa;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"}")
        self.cb_ncc.setObjectName("cb_ncc")
        self.cb_ncc.addItem("")
        self.cb_ncc.addItem("")
        self.lb_ndh = QtWidgets.QLabel(parent=Dialog)
        self.lb_ndh.setGeometry(QtCore.QRect(20, 110, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_ndh.setFont(font)
        self.lb_ndh.setStyleSheet("color: white;")
        self.lb_ndh.setObjectName("lb_ndh")
        self.lb_tgghdk = QtWidgets.QLabel(parent=Dialog)
        self.lb_tgghdk.setGeometry(QtCore.QRect(320, 120, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_tgghdk.setFont(font)
        self.lb_tgghdk.setStyleSheet("color: white;")
        self.lb_tgghdk.setObjectName("lb_tgghdk")
        self.de_tgghdk = QtWidgets.QDateEdit(parent=Dialog)
        self.de_tgghdk.setGeometry(QtCore.QRect(430, 120, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.de_tgghdk.setFont(font)
        self.de_tgghdk.setStyleSheet("QDateEdit{\n"
"    background-color: #A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;\n"
"}\n"
"\n"
"QDateEdit:hover{\n"
"    border: 1px solid #60a5fa;\n"
"}\n"
"\n"
"QDateEdit::drop-down{\n"
"    border: none;\n"
"}\n"
"\n"
"QDateEdit::down-arrow{\n"
"    image: none;\n"
"}")
        self.de_tgghdk.setObjectName("de_tgghdk")
        self.lb_ddgh = QtWidgets.QLabel(parent=Dialog)
        self.lb_ddgh.setGeometry(QtCore.QRect(20, 340, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_ddgh.setFont(font)
        self.lb_ddgh.setStyleSheet("color: white;")
        self.lb_ddgh.setObjectName("lb_ddgh")
        self.ln_tddh = QtWidgets.QFrame(parent=Dialog)
        self.ln_tddh.setGeometry(QtCore.QRect(0, 290, 631, 2))
        self.ln_tddh.setStyleSheet("background-color: #2f4752;\n"
"border: none;\n"
"max-height: 2px;")
        self.ln_tddh.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.ln_tddh.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.ln_tddh.setObjectName("ln_tddh")
        self.pb_hb = QtWidgets.QPushButton(parent=Dialog)
        self.pb_hb.setGeometry(QtCore.QRect(240, 690, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pb_hb.setFont(font)
        self.pb_hb.setStyleSheet("QPushButton{\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #d1d5db;\n"
"    border-radius: 8px;\n"
"    padding: 6px 14px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #f3f4f6;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #e5e7eb;\n"
"}")
        self.pb_hb.setObjectName("pb_hb")
        self.pb_td = QtWidgets.QPushButton(parent=Dialog)
        self.pb_td.setGeometry(QtCore.QRect(320, 690, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.pb_td.setFont(font)
        self.pb_td.setStyleSheet("QPushButton{\n"
"    background-color: #2EC4B6;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 6px 16px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #0ea5a4;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #0d9488;\n"
"}")
        self.pb_td.setObjectName("pb_td")
        self.lb_ncc_2 = QtWidgets.QLabel(parent=Dialog)
        self.lb_ncc_2.setGeometry(QtCore.QRect(20, 170, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_ncc_2.setFont(font)
        self.lb_ncc_2.setStyleSheet("color: white;")
        self.lb_ncc_2.setObjectName("lb_ncc_2")
        self.cb_ncc_2 = QtWidgets.QComboBox(parent=Dialog)
        self.cb_ncc_2.setGeometry(QtCore.QRect(130, 170, 471, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.cb_ncc_2.setFont(font)
        self.cb_ncc_2.setStyleSheet("QComboBox {\n"
"    background-color:#A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid #60a5fa;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"}")
        self.cb_ncc_2.setObjectName("cb_ncc_2")
        self.cb_ncc_2.addItem("")
        self.lb_ncc_3 = QtWidgets.QLabel(parent=Dialog)
        self.lb_ncc_3.setGeometry(QtCore.QRect(20, 210, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_ncc_3.setFont(font)
        self.lb_ncc_3.setStyleSheet("color: white;")
        self.lb_ncc_3.setObjectName("lb_ncc_3")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(130, 210, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.label.setFont(font)
        self.label.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.label.setStyleSheet(" background-color:#A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.lb_ncc_4 = QtWidgets.QLabel(parent=Dialog)
        self.lb_ncc_4.setGeometry(QtCore.QRect(320, 210, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_ncc_4.setFont(font)
        self.lb_ncc_4.setStyleSheet("color: white;")
        self.lb_ncc_4.setObjectName("lb_ncc_4")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(430, 210, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.label_2.setFont(font)
        self.label_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.label_2.setStyleSheet(" background-color:#A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.cb_ddgh = QtWidgets.QComboBox(parent=Dialog)
        self.cb_ddgh.setGeometry(QtCore.QRect(130, 330, 471, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.cb_ddgh.setFont(font)
        self.cb_ddgh.setStyleSheet("QComboBox {\n"
"    background-color:#A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid #60a5fa;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"}")
        self.cb_ddgh.setObjectName("cb_ddgh")
        self.cb_ddgh.addItem("")
        self.cb_ddgh.addItem("")
        self.cb_ddgh.addItem("")
        self.pb_add = QtWidgets.QPushButton(parent=Dialog)
        self.pb_add.setGeometry(QtCore.QRect(20, 250, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.pb_add.setFont(font)
        self.pb_add.setStyleSheet("QPushButton{\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #d1d5db;\n"
"    border-radius: 8px;\n"
"    padding: 6px 14px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #f3f4f6;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #e5e7eb;\n"
"}")
        self.pb_add.setObjectName("pb_add")
        self.lb_ncc_5 = QtWidgets.QLabel(parent=Dialog)
        self.lb_ncc_5.setGeometry(QtCore.QRect(20, 300, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_ncc_5.setFont(font)
        self.lb_ncc_5.setStyleSheet("color: white;")
        self.lb_ncc_5.setObjectName("lb_ncc_5")
        self.lb_ddgh_2 = QtWidgets.QLabel(parent=Dialog)
        self.lb_ddgh_2.setGeometry(QtCore.QRect(20, 370, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_ddgh_2.setFont(font)
        self.lb_ddgh_2.setStyleSheet("color: white;")
        self.lb_ddgh_2.setObjectName("lb_ddgh_2")
        self.cb_ddgh_2 = QtWidgets.QComboBox(parent=Dialog)
        self.cb_ddgh_2.setGeometry(QtCore.QRect(130, 370, 471, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.cb_ddgh_2.setFont(font)
        self.cb_ddgh_2.setStyleSheet("QComboBox {\n"
"    background-color:#A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid #60a5fa;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"}")
        self.cb_ddgh_2.setObjectName("cb_ddgh_2")
        self.cb_ddgh_2.addItem("")
        self.lb_ddgh_3 = QtWidgets.QLabel(parent=Dialog)
        self.lb_ddgh_3.setGeometry(QtCore.QRect(20, 410, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_ddgh_3.setFont(font)
        self.lb_ddgh_3.setStyleSheet("color: white;")
        self.lb_ddgh_3.setObjectName("lb_ddgh_3")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(130, 410, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.label_3.setFont(font)
        self.label_3.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.label_3.setStyleSheet(" background-color:#A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.lb_ddgh_4 = QtWidgets.QLabel(parent=Dialog)
        self.lb_ddgh_4.setGeometry(QtCore.QRect(330, 410, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_ddgh_4.setFont(font)
        self.lb_ddgh_4.setStyleSheet("color: white;")
        self.lb_ddgh_4.setObjectName("lb_ddgh_4")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(430, 410, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.label_4.setFont(font)
        self.label_4.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.label_4.setStyleSheet(" background-color:#A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.lb_ddgh_5 = QtWidgets.QLabel(parent=Dialog)
        self.lb_ddgh_5.setGeometry(QtCore.QRect(20, 450, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_ddgh_5.setFont(font)
        self.lb_ddgh_5.setStyleSheet("color: white;")
        self.lb_ddgh_5.setObjectName("lb_ddgh_5")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(130, 450, 471, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.label_5.setFont(font)
        self.label_5.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.label_5.setStyleSheet(" background-color:#A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.ln_tddh_2 = QtWidgets.QFrame(parent=Dialog)
        self.ln_tddh_2.setGeometry(QtCore.QRect(0, 490, 631, 2))
        self.ln_tddh_2.setStyleSheet("background-color: #2f4752;\n"
"border: none;\n"
"max-height: 2px;")
        self.ln_tddh_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.ln_tddh_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.ln_tddh_2.setObjectName("ln_tddh_2")
        self.fr_tddh = QtWidgets.QFrame(parent=Dialog)
        self.fr_tddh.setGeometry(QtCore.QRect(20, 499, 581, 181))
        self.fr_tddh.setStyleSheet("background-color: #2f4752;\n"
"border: none;\n"
"border-radius: 10px;\n"
"padding: 6px 16px;\n"
"font-weight: 600;")
        self.fr_tddh.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.fr_tddh.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.fr_tddh.setObjectName("fr_tddh")
        self.lb_pvc = QtWidgets.QLabel(parent=self.fr_tddh)
        self.lb_pvc.setGeometry(QtCore.QRect(0, 40, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lb_pvc.setFont(font)
        self.lb_pvc.setStyleSheet("color: #AFC4CF;")
        self.lb_pvc.setObjectName("lb_pvc")
        self.lb_pvc_2 = QtWidgets.QLabel(parent=self.fr_tddh)
        self.lb_pvc_2.setGeometry(QtCore.QRect(0, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lb_pvc_2.setFont(font)
        self.lb_pvc_2.setStyleSheet("color: #AFC4CF;")
        self.lb_pvc_2.setObjectName("lb_pvc_2")
        self.lb_pvc_3 = QtWidgets.QLabel(parent=self.fr_tddh)
        self.lb_pvc_3.setGeometry(QtCore.QRect(0, 70, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lb_pvc_3.setFont(font)
        self.lb_pvc_3.setStyleSheet("color: #AFC4CF;")
        self.lb_pvc_3.setObjectName("lb_pvc_3")
        self.lb_pvc_4 = QtWidgets.QLabel(parent=self.fr_tddh)
        self.lb_pvc_4.setGeometry(QtCore.QRect(0, 120, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lb_pvc_4.setFont(font)
        self.lb_pvc_4.setStyleSheet("color: #AFC4CF;")
        self.lb_pvc_4.setObjectName("lb_pvc_4")
        self.ln_tddh_3 = QtWidgets.QFrame(parent=self.fr_tddh)
        self.ln_tddh_3.setGeometry(QtCore.QRect(-10, 110, 631, 2))
        self.ln_tddh_3.setStyleSheet("background-color: #AFC4CF;;\n"
"border: none;\n"
"max-height: 2px;")
        self.ln_tddh_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.ln_tddh_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.ln_tddh_3.setObjectName("ln_tddh_3")
        self.lb_ddgh_6 = QtWidgets.QLabel(parent=self.fr_tddh)
        self.lb_ddgh_6.setGeometry(QtCore.QRect(430, 10, 141, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lb_ddgh_6.setFont(font)
        self.lb_ddgh_6.setStyleSheet("color: white;")
        self.lb_ddgh_6.setObjectName("lb_ddgh_6")
        self.lb_ddgh_7 = QtWidgets.QLabel(parent=self.fr_tddh)
        self.lb_ddgh_7.setGeometry(QtCore.QRect(440, 40, 211, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lb_ddgh_7.setFont(font)
        self.lb_ddgh_7.setStyleSheet("color: lightyellow;")
        self.lb_ddgh_7.setObjectName("lb_ddgh_7")
        self.lb_ddgh_8 = QtWidgets.QLabel(parent=self.fr_tddh)
        self.lb_ddgh_8.setGeometry(QtCore.QRect(440, 70, 211, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lb_ddgh_8.setFont(font)
        self.lb_ddgh_8.setStyleSheet("color: lightblue;")
        self.lb_ddgh_8.setObjectName("lb_ddgh_8")
        self.lb_ddgh_9 = QtWidgets.QLabel(parent=self.fr_tddh)
        self.lb_ddgh_9.setGeometry(QtCore.QRect(420, 120, 141, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lb_ddgh_9.setFont(font)
        self.lb_ddgh_9.setStyleSheet("color: lightgreen;")
        self.lb_ddgh_9.setObjectName("lb_ddgh_9")
        self.lb_ncc_5.raise_()
        self.lb_tddh.raise_()
        self.de_ndh.raise_()
        self.lb_ncc.raise_()
        self.cb_ncc.raise_()
        self.lb_ndh.raise_()
        self.lb_tgghdk.raise_()
        self.de_tgghdk.raise_()
        self.lb_ddgh.raise_()
        self.ln_tddh.raise_()
        self.pb_hb.raise_()
        self.pb_td.raise_()
        self.lb_ncc_2.raise_()
        self.cb_ncc_2.raise_()
        self.lb_ncc_3.raise_()
        self.label.raise_()
        self.lb_ncc_4.raise_()
        self.label_2.raise_()
        self.cb_ddgh.raise_()
        self.pb_add.raise_()
        self.lb_ddgh_2.raise_()
        self.cb_ddgh_2.raise_()
        self.lb_ddgh_3.raise_()
        self.label_3.raise_()
        self.lb_ddgh_4.raise_()
        self.label_4.raise_()
        self.lb_ddgh_5.raise_()
        self.label_5.raise_()
        self.ln_tddh_2.raise_()
        self.fr_tddh.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lb_tddh.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Tạo Đơn Đặt Hàng</span></p></body></html>"))
        self.lb_ncc.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Nhà cung cấp:</span></p></body></html>"))
        self.cb_ncc.setItemText(0, _translate("Dialog", "ABC"))
        self.cb_ncc.setItemText(1, _translate("Dialog", "DEF"))
        self.lb_ndh.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Ngày đặt hàng:</span></p></body></html>"))
        self.lb_tgghdk.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Ngày giao hàng:</span></p></body></html>"))
        self.lb_ddgh.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Địa điểm giao:</span></p><p><br/></p></body></html>"))
        self.pb_hb.setText(_translate("Dialog", "Hủy bỏ"))
        self.pb_td.setText(_translate("Dialog", "Tạo đơn hàng"))
        self.lb_ncc_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Sản phẩm:</span></p></body></html>"))
        self.cb_ncc_2.setItemText(0, _translate("Dialog", "Chuột Không Dây"))
        self.lb_ncc_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Số lượng:</span></p></body></html>"))
        self.lb_ncc_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Đơn giá:</span></p></body></html>"))
        self.cb_ddgh.setItemText(0, _translate("Dialog", "Kho 1"))
        self.cb_ddgh.setItemText(1, _translate("Dialog", "Kho 2"))
        self.cb_ddgh.setItemText(2, _translate("Dialog", "Kho 3"))
        self.pb_add.setText(_translate("Dialog", "➕ Thêm SP"))
        self.lb_ncc_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Chi phí vận chuyển</span></p></body></html>"))
        self.lb_ddgh_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Phương thức:</span></p></body></html>"))
        self.cb_ddgh_2.setItemText(0, _translate("Dialog", "Tiêu chuẩn (3-5 ngày)"))
        self.lb_ddgh_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Trọng lượng (kg):</span></p></body></html>"))
        self.lb_ddgh_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Ưu tiên:</span></p></body></html>"))
        self.lb_ddgh_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Ghi chú:</span></p></body></html>"))
        self.lb_pvc.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:400;\">Phí vận chuyển:</span></p></body></html>"))
        self.lb_pvc_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:400;\">Tiền hàng:</span></p></body></html>"))
        self.lb_pvc_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:400;\">Phụ phí ưu tiên:</span></p></body></html>"))
        self.lb_pvc_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">TỔNG CỘNG:</span></p></body></html>"))
        self.lb_ddgh_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">15.000.000 VND</span></p></body></html>"))
        self.lb_ddgh_7.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">300.000 VND</span></p></body></html>"))
        self.lb_ddgh_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">300.000 VND</span></p></body></html>"))
        self.lb_ddgh_9.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt;\">15.600.000 VND</span></p></body></html>"))
