# Form implementation generated from reading ui file 'Taohoadon.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(522, 463)
        Dialog.setStyleSheet("background-color: #0F1E25;")
        self.lb_thd = QtWidgets.QLabel(parent=Dialog)
        self.lb_thd.setGeometry(QtCore.QRect(200, 10, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_thd.setFont(font)
        self.lb_thd.setStyleSheet("color: white;")
        self.lb_thd.setObjectName("lb_thd")
        self.lb_shd = QtWidgets.QLabel(parent=Dialog)
        self.lb_shd.setGeometry(QtCore.QRect(30, 60, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_shd.setFont(font)
        self.lb_shd.setStyleSheet("color: white;")
        self.lb_shd.setObjectName("lb_shd")
        self.lb_tkh = QtWidgets.QLabel(parent=Dialog)
        self.lb_tkh.setGeometry(QtCore.QRect(30, 110, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_tkh.setFont(font)
        self.lb_tkh.setStyleSheet("color: white;")
        self.lb_tkh.setObjectName("lb_tkh")
        self.lb_ndathang = QtWidgets.QLabel(parent=Dialog)
        self.lb_ndathang.setGeometry(QtCore.QRect(30, 160, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_ndathang.setFont(font)
        self.lb_ndathang.setStyleSheet("color: white;")
        self.lb_ndathang.setObjectName("lb_ndathang")
        self.de_ndathang = QtWidgets.QDateEdit(parent=Dialog)
        self.de_ndathang.setGeometry(QtCore.QRect(160, 160, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.de_ndathang.setFont(font)
        self.de_ndathang.setStyleSheet("QDateEdit{\n"
"    background-color: #A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;\n"
"}\n"
"\n"
"QDateEdit:hover{\n"
"    border: 1px solid #60a5fa;\n"
"}\n"
"\n"
"QDateEdit::drop-down{\n"
"    border: none;\n"
"}\n"
"\n"
"QDateEdit::down-arrow{\n"
"    image: none;\n"
"}")
        self.de_ndathang.setObjectName("de_ndathang")
        self.lb_ndenhan = QtWidgets.QLabel(parent=Dialog)
        self.lb_ndenhan.setGeometry(QtCore.QRect(30, 210, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_ndenhan.setFont(font)
        self.lb_ndenhan.setStyleSheet("color: white;")
        self.lb_ndenhan.setObjectName("lb_ndenhan")
        self.pb_hb = QtWidgets.QPushButton(parent=Dialog)
        self.pb_hb.setGeometry(QtCore.QRect(164, 380, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pb_hb.setFont(font)
        self.pb_hb.setStyleSheet("QPushButton{\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #d1d5db;\n"
"    border-radius: 8px;\n"
"    padding: 6px 14px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #f3f4f6;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #e5e7eb;\n"
"}")
        self.pb_hb.setObjectName("pb_hb")
        self.pb_thd = QtWidgets.QPushButton(parent=Dialog)
        self.pb_thd.setGeometry(QtCore.QRect(270, 380, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.pb_thd.setFont(font)
        self.pb_thd.setStyleSheet("QPushButton{\n"
"    background-color: #2EC4B6;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 6px 16px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #0ea5a4;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #0d9488;\n"
"}")
        self.pb_thd.setObjectName("pb_thd")
        self.de_ndenhan = QtWidgets.QDateEdit(parent=Dialog)
        self.de_ndenhan.setGeometry(QtCore.QRect(160, 210, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.de_ndenhan.setFont(font)
        self.de_ndenhan.setStyleSheet("QDateEdit{\n"
"    background-color: #A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;\n"
"}\n"
"\n"
"QDateEdit:hover{\n"
"    border: 1px solid #60a5fa;\n"
"}\n"
"\n"
"QDateEdit::drop-down{\n"
"    border: none;\n"
"}\n"
"\n"
"QDateEdit::down-arrow{\n"
"    image: none;\n"
"}")
        self.de_ndenhan.setObjectName("de_ndenhan")
        self.lb_st = QtWidgets.QLabel(parent=Dialog)
        self.lb_st.setGeometry(QtCore.QRect(30, 260, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_st.setFont(font)
        self.lb_st.setStyleSheet("color: white;")
        self.lb_st.setObjectName("lb_st")
        self.lb_tt = QtWidgets.QLabel(parent=Dialog)
        self.lb_tt.setGeometry(QtCore.QRect(30, 310, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_tt.setFont(font)
        self.lb_tt.setStyleSheet("color: white;")
        self.lb_tt.setObjectName("lb_tt")
        self.cb_tt = QtWidgets.QComboBox(parent=Dialog)
        self.cb_tt.setGeometry(QtCore.QRect(160, 310, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.cb_tt.setFont(font)
        self.cb_tt.setStyleSheet("background-color:#A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;")
        self.cb_tt.setEditable(False)
        self.cb_tt.setCurrentText("Tất cả")
        self.cb_tt.setObjectName("cb_tt")
        self.cb_tt.addItem("")
        self.cb_tt.addItem("")
        self.cb_tt.addItem("")
        self.cb_tt.addItem("")
        self.cb_tt.addItem("")
        self.cb_tt.setItemText(4, "")
        self.lne_shd = QtWidgets.QLineEdit(parent=Dialog)
        self.lne_shd.setGeometry(QtCore.QRect(160, 60, 311, 31))
        self.lne_shd.setStyleSheet("background-color:#A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;")
        self.lne_shd.setObjectName("lne_shd")
        self.lne_tkh = QtWidgets.QLineEdit(parent=Dialog)
        self.lne_tkh.setGeometry(QtCore.QRect(160, 110, 311, 31))
        self.lne_tkh.setStyleSheet("background-color:#A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;")
        self.lne_tkh.setObjectName("lne_tkh")
        self.lne_st = QtWidgets.QLineEdit(parent=Dialog)
        self.lne_st.setGeometry(QtCore.QRect(160, 260, 311, 31))
        self.lne_st.setStyleSheet("background-color:#A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;")
        self.lne_st.setObjectName("lne_st")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lb_thd.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Tạo Hóa Đơn</span></p></body></html>"))
        self.lb_shd.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Số hóa đơn:</span></p></body></html>"))
        self.lb_tkh.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Tên khách hàng:</span></p></body></html>"))
        self.lb_ndathang.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Ngày đặt hàng:</span></p></body></html>"))
        self.lb_ndenhan.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Ngày đến hạn:</span></p></body></html>"))
        self.pb_hb.setText(_translate("Dialog", "Hủy bỏ"))
        self.pb_thd.setText(_translate("Dialog", "Tạo hóa đơn"))
        self.lb_st.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Số tiền:</span></p></body></html>"))
        self.lb_tt.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Trạng thái:</span></p></body></html>"))
        self.cb_tt.setItemText(0, _translate("Dialog", "Tất cả"))
        self.cb_tt.setItemText(1, _translate("Dialog", "Đã thanh toán"))
        self.cb_tt.setItemText(2, _translate("Dialog", "Quá hạn"))
        self.cb_tt.setItemText(3, _translate("Dialog", "Chưa giải quyết"))
