# Form implementation generated from reading ui file 'ThemKH.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(522, 463)
        Dialog.setStyleSheet("background-color: #0F1E25;")
        self.lb_tkh = QtWidgets.QLabel(parent=Dialog)
        self.lb_tkh.setGeometry(QtCore.QRect(160, 10, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_tkh.setFont(font)
        self.lb_tkh.setStyleSheet("color: white;")
        self.lb_tkh.setObjectName("lb_tkh")
        self.lb_stt = QtWidgets.QLabel(parent=Dialog)
        self.lb_stt.setGeometry(QtCore.QRect(30, 60, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_stt.setFont(font)
        self.lb_stt.setStyleSheet("color: white;")
        self.lb_stt.setObjectName("lb_stt")
        self.lb_tkh_2 = QtWidgets.QLabel(parent=Dialog)
        self.lb_tkh_2.setGeometry(QtCore.QRect(30, 110, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_tkh_2.setFont(font)
        self.lb_tkh_2.setStyleSheet("color: white;")
        self.lb_tkh_2.setObjectName("lb_tkh_2")
        self.lb_email = QtWidgets.QLabel(parent=Dialog)
        self.lb_email.setGeometry(QtCore.QRect(30, 160, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_email.setFont(font)
        self.lb_email.setStyleSheet("color: white;")
        self.lb_email.setObjectName("lb_email")
        self.lb_sdt = QtWidgets.QLabel(parent=Dialog)
        self.lb_sdt.setGeometry(QtCore.QRect(30, 210, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_sdt.setFont(font)
        self.lb_sdt.setStyleSheet("color: white;")
        self.lb_sdt.setObjectName("lb_sdt")
        self.pb_hb = QtWidgets.QPushButton(parent=Dialog)
        self.pb_hb.setGeometry(QtCore.QRect(180, 380, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pb_hb.setFont(font)
        self.pb_hb.setStyleSheet("QPushButton{\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #d1d5db;\n"
"    border-radius: 8px;\n"
"    padding: 6px 14px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #f3f4f6;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #e5e7eb;\n"
"}")
        self.pb_hb.setObjectName("pb_hb")
        self.pb_thd = QtWidgets.QPushButton(parent=Dialog)
        self.pb_thd.setGeometry(QtCore.QRect(280, 380, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.pb_thd.setFont(font)
        self.pb_thd.setStyleSheet("QPushButton{\n"
"    background-color: #2EC4B6;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 6px 16px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #0ea5a4;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #0d9488;\n"
"}")
        self.pb_thd.setObjectName("pb_thd")
        self.lb_tdh = QtWidgets.QLabel(parent=Dialog)
        self.lb_tdh.setGeometry(QtCore.QRect(30, 260, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_tdh.setFont(font)
        self.lb_tdh.setStyleSheet("color: white;")
        self.lb_tdh.setObjectName("lb_tdh")
        self.lb_tt = QtWidgets.QLabel(parent=Dialog)
        self.lb_tt.setGeometry(QtCore.QRect(30, 310, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_tt.setFont(font)
        self.lb_tt.setStyleSheet("color: white;")
        self.lb_tt.setObjectName("lb_tt")
        self.lne_stt = QtWidgets.QLineEdit(parent=Dialog)
        self.lne_stt.setGeometry(QtCore.QRect(160, 60, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lne_stt.setFont(font)
        self.lne_stt.setStyleSheet("background-color:#A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;")
        self.lne_stt.setObjectName("lne_stt")
        self.lne_tkh = QtWidgets.QLineEdit(parent=Dialog)
        self.lne_tkh.setGeometry(QtCore.QRect(160, 110, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lne_tkh.setFont(font)
        self.lne_tkh.setStyleSheet("background-color:#A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;")
        self.lne_tkh.setObjectName("lne_tkh")
        self.lne_sdt = QtWidgets.QLineEdit(parent=Dialog)
        self.lne_sdt.setGeometry(QtCore.QRect(160, 210, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lne_sdt.setFont(font)
        self.lne_sdt.setStyleSheet("background-color:#A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;")
        self.lne_sdt.setObjectName("lne_sdt")
        self.lne_email = QtWidgets.QLineEdit(parent=Dialog)
        self.lne_email.setGeometry(QtCore.QRect(160, 160, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lne_email.setFont(font)
        self.lne_email.setStyleSheet("background-color:#A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;")
        self.lne_email.setObjectName("lne_email")
        self.spb_tdh = QtWidgets.QSpinBox(parent=Dialog)
        self.spb_tdh.setGeometry(QtCore.QRect(160, 260, 311, 31))
        self.spb_tdh.setStyleSheet("background-color:#A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;")
        self.spb_tdh.setObjectName("spb_tdh")
        self.cb_tt = QtWidgets.QComboBox(parent=Dialog)
        self.cb_tt.setGeometry(QtCore.QRect(160, 310, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.cb_tt.setFont(font)
        self.cb_tt.setStyleSheet("background-color:#A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;")
        self.cb_tt.setEditable(False)
        self.cb_tt.setCurrentText("Tất cả")
        self.cb_tt.setObjectName("cb_tt")
        self.cb_tt.addItem("")
        self.cb_tt.addItem("")
        self.cb_tt.addItem("")
        self.cb_tt.addItem("")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lb_tkh.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Thêm Khách Hàng</span></p></body></html>"))
        self.lb_stt.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Số thứ tự:</span></p></body></html>"))
        self.lb_tkh_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Tên khách hàng:</span></p></body></html>"))
        self.lb_email.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Email:</span></p></body></html>"))
        self.lb_sdt.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">SĐT:</span></p></body></html>"))
        self.pb_hb.setText(_translate("Dialog", "Hủy bỏ"))
        self.pb_thd.setText(_translate("Dialog", "Thêm"))
        self.lb_tdh.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Tổng Đơn Hàng</span></p></body></html>"))
        self.lb_tt.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Trạng thái:</span></p></body></html>"))
        self.cb_tt.setItemText(0, _translate("Dialog", "Tất cả"))
        self.cb_tt.setItemText(1, _translate("Dialog", "VIP"))
        self.cb_tt.setItemText(2, _translate("Dialog", "Đã lâu"))
        self.cb_tt.setItemText(3, _translate("Dialog", "Gần đây"))
