# Form implementation generated from reading ui file 'ThemSP.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(522, 463)
        Dialog.setStyleSheet("background-color: #0F1E25;")
        self.lb_tsp = QtWidgets.QLabel(parent=Dialog)
        self.lb_tsp.setGeometry(QtCore.QRect(200, 10, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_tsp.setFont(font)
        self.lb_tsp.setStyleSheet("color: white;")
        self.lb_tsp.setObjectName("lb_tsp")
        self.lb_msp = QtWidgets.QLabel(parent=Dialog)
        self.lb_msp.setGeometry(QtCore.QRect(30, 60, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_msp.setFont(font)
        self.lb_msp.setStyleSheet("color: white;")
        self.lb_msp.setObjectName("lb_msp")
        self.lb_tsp_2 = QtWidgets.QLabel(parent=Dialog)
        self.lb_tsp_2.setGeometry(QtCore.QRect(30, 110, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_tsp_2.setFont(font)
        self.lb_tsp_2.setStyleSheet("color: white;")
        self.lb_tsp_2.setObjectName("lb_tsp_2")
        self.lb_pl = QtWidgets.QLabel(parent=Dialog)
        self.lb_pl.setGeometry(QtCore.QRect(30, 160, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_pl.setFont(font)
        self.lb_pl.setStyleSheet("color: white;")
        self.lb_pl.setObjectName("lb_pl")
        self.lb_sl = QtWidgets.QLabel(parent=Dialog)
        self.lb_sl.setGeometry(QtCore.QRect(30, 210, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_sl.setFont(font)
        self.lb_sl.setStyleSheet("color: white;")
        self.lb_sl.setObjectName("lb_sl")
        self.pb_hb = QtWidgets.QPushButton(parent=Dialog)
        self.pb_hb.setGeometry(QtCore.QRect(164, 380, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pb_hb.setFont(font)
        self.pb_hb.setStyleSheet("QPushButton{\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #d1d5db;\n"
"    border-radius: 8px;\n"
"    padding: 6px 14px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #f3f4f6;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #e5e7eb;\n"
"}")
        self.pb_hb.setObjectName("pb_hb")
        self.pb_tsp = QtWidgets.QPushButton(parent=Dialog)
        self.pb_tsp.setGeometry(QtCore.QRect(270, 380, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.pb_tsp.setFont(font)
        self.pb_tsp.setStyleSheet("QPushButton{\n"
"    background-color: #2EC4B6;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 6px 16px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #0ea5a4;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #0d9488;\n"
"}")
        self.pb_tsp.setObjectName("pb_tsp")
        self.lb_gb = QtWidgets.QLabel(parent=Dialog)
        self.lb_gb.setGeometry(QtCore.QRect(30, 260, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_gb.setFont(font)
        self.lb_gb.setStyleSheet("color: white;")
        self.lb_gb.setObjectName("lb_gb")
        self.lb_tt = QtWidgets.QLabel(parent=Dialog)
        self.lb_tt.setGeometry(QtCore.QRect(30, 310, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.lb_tt.setFont(font)
        self.lb_tt.setStyleSheet("color: white;")
        self.lb_tt.setObjectName("lb_tt")
        self.cb_tt = QtWidgets.QComboBox(parent=Dialog)
        self.cb_tt.setGeometry(QtCore.QRect(160, 310, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.cb_tt.setFont(font)
        self.cb_tt.setStyleSheet("background-color:#A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;")
        self.cb_tt.setEditable(False)
        self.cb_tt.setCurrentText("Tất cả")
        self.cb_tt.setObjectName("cb_tt")
        self.cb_tt.addItem("")
        self.cb_tt.addItem("")
        self.cb_tt.addItem("")
        self.cb_tt.addItem("")
        self.cb_tt.addItem("")
        self.cb_tt.setItemText(4, "")
        self.lne_msp = QtWidgets.QLineEdit(parent=Dialog)
        self.lne_msp.setGeometry(QtCore.QRect(160, 60, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lne_msp.setFont(font)
        self.lne_msp.setStyleSheet("background-color:#A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;")
        self.lne_msp.setObjectName("lne_msp")
        self.lne_tsp = QtWidgets.QLineEdit(parent=Dialog)
        self.lne_tsp.setGeometry(QtCore.QRect(160, 110, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lne_tsp.setFont(font)
        self.lne_tsp.setStyleSheet("background-color:#A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;")
        self.lne_tsp.setObjectName("lne_tsp")
        self.lne_gb = QtWidgets.QLineEdit(parent=Dialog)
        self.lne_gb.setGeometry(QtCore.QRect(160, 260, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lne_gb.setFont(font)
        self.lne_gb.setStyleSheet("background-color:#A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;")
        self.lne_gb.setObjectName("lne_gb")
        self.cb_pl = QtWidgets.QComboBox(parent=Dialog)
        self.cb_pl.setGeometry(QtCore.QRect(160, 160, 311, 31))
        self.cb_pl.setStyleSheet("background-color:#A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;")
        self.cb_pl.setObjectName("cb_pl")
        self.spb_sl = QtWidgets.QSpinBox(parent=Dialog)
        self.spb_sl.setGeometry(QtCore.QRect(160, 211, 311, 31))
        self.spb_sl.setStyleSheet("background-color:#A6C8D8;\n"
"    border: 1px solid #bfdbfe;\n"
"    border-radius: 8px;\n"
"    padding: 4px 8px;\n"
"    color: #1e293b;")
        self.spb_sl.setObjectName("spb_sl")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lb_tsp.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Thêm Sản Phẩm</span></p></body></html>"))
        self.lb_msp.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Mã sản phẩm:</span></p></body></html>"))
        self.lb_tsp_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Tên sản phẩm:</span></p></body></html>"))
        self.lb_pl.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Phân loại:</span></p></body></html>"))
        self.lb_sl.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Số lượng</span></p></body></html>"))
        self.pb_hb.setText(_translate("Dialog", "Hủy bỏ"))
        self.pb_tsp.setText(_translate("Dialog", "Thêm sản phẩm"))
        self.lb_gb.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Giá bán:</span></p></body></html>"))
        self.lb_tt.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Trạng thái:</span></p></body></html>"))
        self.cb_tt.setItemText(0, _translate("Dialog", "Tất cả"))
        self.cb_tt.setItemText(1, _translate("Dialog", "Tồn kho thấp"))
        self.cb_tt.setItemText(2, _translate("Dialog", "Hết hàng"))
        self.cb_tt.setItemText(3, _translate("Dialog", "Còn hàng"))
